from ottobuzzer import OttoBuzzer

buzzer = OttoBuzzer(25)      # Built in Buzzer

buzzer.playNote(261, 125)
buzzer.playNote(293, 125)
buzzer.playNote(329, 125)
buzzer.playNote(349, 125)
buzzer.playNote(392, 125)
buzzer.playNote(440, 125)
buzzer.playNote(493, 125)
buzzer.playNote(523, 125)

buzzer.playEmoji("S_connection")
buzzer.playEmoji("S_disconnection")
buzzer.playEmoji("S_buttonPushed")
buzzer.playEmoji("S_mode1")
buzzer.playEmoji("S_mode2")
buzzer.playEmoji("S_mode3")
buzzer.playEmoji("S_surprise")
buzzer.playEmoji("S_JUMP")
buzzer.playEmoji("S_OhOoh")
buzzer.playEmoji("S_OhOoh2")
buzzer.playEmoji("S_cuddly")
buzzer.playEmoji("S_sleeping")
buzzer.playEmoji("S_happy")
buzzer.playEmoji("S_superHappy")
buzzer.playEmoji("S_happy_short")
buzzer.playEmoji("S_sad")
buzzer.playEmoji("S_confused")
buzzer.playEmoji("S_fart1")
buzzer.playEmoji("S_fart2")
buzzer.playEmoji("S_fart3")

#buzzer.execute_RTTTL('Flinstones')
#buzzer.execute_RTTTL('StarWars')
#buzzer.execute_RTTTL('MahnaMahna')
#buzzer.execute_RTTTL('LeisureSuit')
#buzzer.execute_RTTTL('Entertainer')
#buzzer.execute_RTTTL('Muppets')
#buzzer.execute_RTTTL('The_Simpsons')
#buzzer.execute_RTTTL('Indiana')
#buzzer.execute_RTTTL('TakeOnMe')
#buzzer.execute_RTTTL('Looney')
#buzzer.execute_RTTTL('20thCenFox')
#buzzer.execute_RTTTL('Bond')
#buzzer.execute_RTTTL('GoodBad')
#buzzer.execute_RTTTL('Jeopardy')
#buzzer.execute_RTTTL('Gadget')
#buzzer.execute_RTTTL('Smurfs')
#buzzer.execute_RTTTL('Super Mario - Main Theme')
#buzzer.execute_RTTTL('Super Mario - Title Music')
#buzzer.execute_RTTTL('SMBtheme')
#buzzer.execute_RTTTL('SMBwater')
#buzzer.execute_RTTTL('SMBunderground')
#buzzer.execute_RTTTL('Picaxe')
#buzzer.execute_RTTTL('Xfiles')
#buzzer.execute_RTTTL('TopGun')
#buzzer.execute_RTTTL('MASH')
#buzzer.execute_RTTTL('tetris')
#buzzer.execute_RTTTL('Wii_Fit_Ob')
#buzzer.execute_RTTTL('Dryer_Song')
#buzzer.execute_RTTTL('One')